name: unibet-event-goals-batch

on:
  workflow_dispatch:

jobs:
  run-batch:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Say hello
        run: echo "hello from runner"

      - name: Show pwd
        run: pwd

      - name: List files
        run: ls -la
